fail_fast: false
exclude: |
  (?x)^(
      docs/ |
      another/example/directory/to_exclude/
  )|(?x)^(
      example/file/to_exclude.py |
      another/example/file/to_exclude.py
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        name: autoflake
        args: ["--in-place", "--remove-unused-variables", "--remove-all-unused-imports"]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)

  - repo: local
    hooks:
      - id: markdownlint
        name: markdownlint
        entry: markdownlint --fix
        language: system
        types: [markdown]

      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: ["--line-length", "119"]

      - id: prettier
        name: prettier
        entry: prettier --write --list-different --ignore-unknown
        language: system
        types_or: [css, javascript, html, yaml, json, markdown]

      - id: eslint
        name: eslint
        entry: eslint
        language: system
        types: [javascript]
        args: [--fix]
      # additional_dependencies: [eslint@8.15.0, eslint-config-prettier@8.5.0, eslint-plugin-no-unsanitized@4.0.1]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: name-tests-test
        fail_fast: true # applies to name-tests-test as well as every hook below
      - id: no-commit-to-branch
        stages: [commit]

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v6.5.0
    hooks:
      - id: cspell
        args: [--config, .cspell.yaml, --no-summary, --gitignore, --no-progress]
        types_or: [css, javascript, html, markdown, python]

  - repo: https://github.com/PyCQA/doc8
    rev: 0.11.2
    hooks:
      - id: doc8
        args: ["--max-line-length", "119", "--file-encoding", "utf-8"]

  - repo: https://github.com/Lucas-C/pre-commit-hooks-java
    rev: 1.3.10
    hooks:
      - id: validate-html
        exclude: ^tests/
        name: html validate

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: [--config, .flake8.ini]
      # additional_dependencies: [ flake8-pytest-style, flake8-bugbear, flake8-comprehensions, flake8-print, darglint]
      # and maybe add flake8-simplify?

      - id: restructuredtext_lint
        exclude: ^docs-src/ # exclude docs src because that is sphinx rst not normal rst (doc8 is for sphinx)
        name: rst lint
        entry: rst-lint --encoding utf-8
        additional_dependencies: [restructuredtext_lint]
        types: [rst]
        language: python

      - id: bandit
        name: bandit
        entry: bandit
        language: system
        types: [python]
        args: [--severity-level=high, --confidence-level=high]

      - id: stylelint
        name: stylelint
        entry: stylelint
        language: system
        files: \.(css|scss|sass)$
      # additional_dependencies: [stylelint@14.8.2, stylelint-config-standard@25.0.0, stylelint-config-prettier@9.0.3]

      - id: pylint
        name: pylint
        entry: pylint
        language: system
        verbose: true
        types: [python]
        args: [--rcfile, .pylintrc.ini, --score=n]
