fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.1
    hooks:
      - id: markdownlint-fix

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: prettier --write --list-different --ignore-unknown
        language: node
        types_or: [css, javascript, html, yaml, json, markdown]
        additional_dependencies: [prettier@2.7.1]
